// Flutter icons DamyoIcon
// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// To use this font, place it in your fonts/ directory and include the
// following in your pubspec.yaml
//
// flutter:
//   fonts:
//    - family:  DamyoIcon
//      fonts:
//       - asset: fonts/DamyoIcon.ttf
//
// 
// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
//         Author:    Just Be Nice studio
//         License:   SIL (http://scripts.sil.org/OFL)
//         Homepage:  http://www.justbenicestudio.com/
// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
//         Author:    Dave Gandy
//         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
//         Homepage:  http://fortawesome.github.com/Font-Awesome/
// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
//         Author:    Dave Gandy
//         License:   SIL ()
//         Homepage:  http://fortawesome.github.com/Font-Awesome/
//
import 'package:flutter/widgets.dart';

class DamyoIcon {
  DamyoIcon._();

  static const _kFontFam = 'DamyoIcon';
  static const String? _kFontPkg = null;

  static const IconData naver = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spot = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoritesFill_2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoritesEmpty_2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoritesEmpty_3 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoritesFill_3 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statisticsEmpty = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statisticsFill = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingFill = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoritesFill = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingEmpty = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favoritesEmpty = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mapEmpty = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mapFill = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mapEmpty_2 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mapFill_2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mapMarker = IconData(0xf041, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mapMarkerAlt = IconData(0xf3c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
